var express = require("express");
var router = express.Router();

/* GET users listing. */

let data = {
  message: "success感谢又拍云(upyun.com)提供CDN赞助",
  status: 200,
  date: "20230214",
  time: "2023-02-14 15:04:51",
  cityInfo: {
    city: "天津市",
    citykey: "101030100",
    parent: "天津",
    updateTime: "12:01",
  },
  data: {
    shidu: "22%",
    pm25: 9,
    pm10: 21,
    quality: "优",
    wendu: "-2",
    ganmao: "各类人群可自由活动",
    forecast: [
      {
        date: "14",
        high: "高温 4℃",
        low: "低温 -2℃",
        ymd: "2023-02-14",
        week: "星期二",
        sunrise: "07:03",
        sunset: "17:46",
        aqi: 21,
        fx: "东风",
        fl: "2级",
        type: "多云",
        notice: "阴晴之间，谨防紫外线侵扰",
      },
      {
        date: "15",
        high: "高温 5℃",
        low: "低温 -2℃",
        ymd: "2023-02-15",
        week: "星期三",
        sunrise: "07:02",
        sunset: "17:47",
        aqi: 66,
        fx: "东南风",
        fl: "2级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
      {
        date: "16",
        high: "高温 7℃",
        low: "低温 0℃",
        ymd: "2023-02-16",
        week: "星期四",
        sunrise: "07:01",
        sunset: "17:48",
        aqi: 98,
        fx: "西南风",
        fl: "2级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
      {
        date: "17",
        high: "高温 7℃",
        low: "低温 1℃",
        ymd: "2023-02-17",
        week: "星期五",
        sunrise: "06:59",
        sunset: "17:50",
        aqi: 117,
        fx: "西南风",
        fl: "2级",
        type: "霾",
        notice: "雾霾来袭，戴好口罩再出门",
      },
      {
        date: "18",
        high: "高温 5℃",
        low: "低温 0℃",
        ymd: "2023-02-18",
        week: "星期六",
        sunrise: "06:58",
        sunset: "17:51",
        aqi: 74,
        fx: "东风",
        fl: "3级",
        type: "小雪",
        notice: "小雪虽美，赏雪别着凉",
      },
      {
        date: "19",
        high: "高温 7℃",
        low: "低温 -2℃",
        ymd: "2023-02-19",
        week: "星期日",
        sunrise: "06:57",
        sunset: "17:52",
        aqi: 30,
        fx: "西北风",
        fl: "4级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
      {
        date: "20",
        high: "高温 6℃",
        low: "低温 0℃",
        ymd: "2023-02-20",
        week: "星期一",
        sunrise: "06:55",
        sunset: "17:53",
        aqi: 33,
        fx: "北风",
        fl: "2级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
      {
        date: "21",
        high: "高温 7℃",
        low: "低温 0℃",
        ymd: "2023-02-21",
        week: "星期二",
        sunrise: "06:54",
        sunset: "17:54",
        aqi: 58,
        fx: "西南风",
        fl: "2级",
        type: "阴",
        notice: "不要被阴云遮挡住好心情",
      },
      {
        date: "22",
        high: "高温 11℃",
        low: "低温 1℃",
        ymd: "2023-02-22",
        week: "星期三",
        sunrise: "06:53",
        sunset: "17:55",
        aqi: 90,
        fx: "西风",
        fl: "2级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
      {
        date: "23",
        high: "高温 15℃",
        low: "低温 3℃",
        ymd: "2023-02-23",
        week: "星期四",
        sunrise: "06:51",
        sunset: "17:56",
        aqi: 79,
        fx: "西南风",
        fl: "2级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
      {
        date: "24",
        high: "高温 15℃",
        low: "低温 3℃",
        ymd: "2023-02-24",
        week: "星期五",
        sunrise: "06:50",
        sunset: "17:57",
        aqi: 79,
        fx: "西南风",
        fl: "3级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
      {
        date: "25",
        high: "高温 8℃",
        low: "低温 1℃",
        ymd: "2023-02-25",
        week: "星期六",
        sunrise: "06:49",
        sunset: "17:58",
        aqi: 78,
        fx: "西北风",
        fl: "2级",
        type: "多云",
        notice: "阴晴之间，谨防紫外线侵扰",
      },
      {
        date: "26",
        high: "高温 16℃",
        low: "低温 2℃",
        ymd: "2023-02-26",
        week: "星期日",
        sunrise: "06:47",
        sunset: "17:59",
        aqi: 87,
        fx: "东北风",
        fl: "2级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
      {
        date: "27",
        high: "高温 11℃",
        low: "低温 2℃",
        ymd: "2023-02-27",
        week: "星期一",
        sunrise: "06:46",
        sunset: "18:00",
        aqi: 124,
        fx: "南风",
        fl: "3级",
        type: "霾",
        notice: "雾霾来袭，戴好口罩再出门",
      },
      {
        date: "28",
        high: "高温 18℃",
        low: "低温 4℃",
        ymd: "2023-02-28",
        week: "星期二",
        sunrise: "06:44",
        sunset: "18:02",
        aqi: 14,
        fx: "东风",
        fl: "2级",
        type: "晴",
        notice: "愿你拥有比阳光明媚的心情",
      },
    ],
    yesterday: {
      date: "13",
      high: "高温 5℃",
      low: "低温 -3℃",
      ymd: "2023-02-13",
      week: "星期一",
      sunrise: "07:04",
      sunset: "17:45",
      aqi: 19,
      fx: "北风",
      fl: "3级",
      type: "晴",
      notice: "愿你拥有比阳光明媚的心情",
    },
  },
};
router.get("/", function (req, res, next) {
  res.send(data);
});

module.exports = router;
